### ISSUE TITLE
[=BUG=] get a TypeError when calling video_info

### ISSUE THREAD

**Issue by ppodds** [play-dl/play-dl#283]
#### Describe the bug

Get a TypeError when calling `video_info`

Work fine in the previous few days, but is broken now.

 - Node.js version: v16.14.0
 - OS & version:  Docker Image (node:16.14.0-bullseye)
 - play-dl version: 1.9.3

#### Actual behavior

get a `TypeError`

#### Expected behavior

get `Promise<InfoData>`

#### Code to reproduce

```js
try {
  const url = https://www.youtube.com/watch?v=Qou76O_Rys0;
  console.log(url);
  const info = await video_info(url);
  console.log(info);
} catch (err) {
  console.log(err);
}
```

#### ScreenShots

![image](https://user-images.githubusercontent.com/11408727/162432313-e27a6b9a-f8ef-4114-a7c4-9e1d3eb2035f.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by absidue** [comment]
Should be fixed in 1.9.4.

**Comment by JakeeArcs** [comment]
Still happens. I get `TypeError: Cannot read properties of undefined (reading 'decoratedPlayerBarRenderer')` when using:
- `video_info` 
- `video_basic_info`
-  `playlist_info`

`search` still works as intended.
